# Generated by Django 5.0.6 on 2024-06-12 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conferency', '0001_initial'),
        ('app_speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='conferency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_conferency.conferency'),
        ),
    ]
