# Generated by Django 5.0.6 on 2024-06-12 12:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_speakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_theme', models.CharField(blank=True, max_length=255, null=True)),
                ('conf_title', models.CharField(blank=True, max_length=255, null=True)),
                ('conf_description', models.TextField(blank=True, null=True)),
                ('conf_date', models.DateField(blank=True, null=True)),
                ('conf_location', models.CharField(blank=True, max_length=255, null=True)),
                ('conf_day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
            options={
                'verbose_name': 'Conferency',
                'verbose_name_plural': 'Conferency',
                'db_table': 'conferency',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(blank=True, max_length=255, null=True)),
                ('session_timestamp', models.DateTimeField(blank=True, null=True)),
                ('session_description', models.TextField(blank=True, null=True)),
                ('conferency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_conferency.conferency')),
                ('session_speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_speakers.speakers')),
            ],
            options={
                'verbose_name': 'Sessions',
                'verbose_name_plural': 'Sessions',
                'db_table': 'sessions',
            },
        ),
    ]
