# Generated by Django 5.0.6 on 2024-06-12 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conferency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencyAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_day', models.DateTimeField(blank=True, null=True)),
                ('agenda_time', models.DateTimeField(blank=True, null=True)),
                ('agenda_title', models.CharField(blank=True, max_length=255, null=True)),
                ('conferency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_conferency.conferency')),
            ],
            options={
                'verbose_name': 'Conferency Agenda',
                'verbose_name_plural': 'Conferency Agenda',
                'db_table': 'conferency_agenda',
            },
        ),
        migrations.CreateModel(
            name='ConferencySections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
                ('section_logo', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('conferency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_conferency.conferency')),
            ],
            options={
                'verbose_name': 'Conferency Sections',
                'verbose_name_plural': 'Conferency Sections',
                'db_table': 'conferency_sections',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('conferency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_conferency.conferency')),
            ],
            options={
                'verbose_name': 'Partners',
                'verbose_name_plural': 'Partners',
                'db_table': 'partners',
            },
        ),
    ]
